/*

Copyright 2017 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

// Code generated by protoc-gen-go.
// source: vmregistry.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	vmregistry.proto

It has these top-level messages:
	VM
	ListVMRequest
	ListVMReply
	FindRequest
	CreateRequest
	DestroyRequest
	DestroyReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindRequest_FindBy int32

const (
	FindRequest_UNSPECIFIED FindRequest_FindBy = 0
	FindRequest_IP          FindRequest_FindBy = 1
	FindRequest_MAC         FindRequest_FindBy = 2
)

var FindRequest_FindBy_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "IP",
	2: "MAC",
}
var FindRequest_FindBy_value = map[string]int32{
	"UNSPECIFIED": 0,
	"IP":          1,
	"MAC":         2,
}

func (x FindRequest_FindBy) String() string {
	return proto.EnumName(FindRequest_FindBy_name, int32(x))
}
func (FindRequest_FindBy) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type VM struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mac  string `protobuf:"bytes,2,opt,name=mac" json:"mac,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
}

func (m *VM) Reset()                    { *m = VM{} }
func (m *VM) String() string            { return proto.CompactTextString(m) }
func (*VM) ProtoMessage()               {}
func (*VM) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VM) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VM) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *VM) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ListVMRequest struct {
}

func (m *ListVMRequest) Reset()                    { *m = ListVMRequest{} }
func (m *ListVMRequest) String() string            { return proto.CompactTextString(m) }
func (*ListVMRequest) ProtoMessage()               {}
func (*ListVMRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListVMReply struct {
	Vms []*VM `protobuf:"bytes,1,rep,name=vms" json:"vms,omitempty"`
}

func (m *ListVMReply) Reset()                    { *m = ListVMReply{} }
func (m *ListVMReply) String() string            { return proto.CompactTextString(m) }
func (*ListVMReply) ProtoMessage()               {}
func (*ListVMReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListVMReply) GetVms() []*VM {
	if m != nil {
		return m.Vms
	}
	return nil
}

type FindRequest struct {
	FindBy FindRequest_FindBy `protobuf:"varint,1,opt,name=find_by,json=findBy,enum=api.FindRequest_FindBy" json:"find_by,omitempty"`
	Value  string             `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *FindRequest) Reset()                    { *m = FindRequest{} }
func (m *FindRequest) String() string            { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()               {}
func (*FindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindRequest) GetFindBy() FindRequest_FindBy {
	if m != nil {
		return m.FindBy
	}
	return FindRequest_UNSPECIFIED
}

func (m *FindRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mem         uint64 `protobuf:"varint,2,opt,name=mem" json:"mem,omitempty"`
	Cores       uint32 `protobuf:"varint,3,opt,name=cores" json:"cores,omitempty"`
	Size        uint64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	SourceImage string `protobuf:"bytes,5,opt,name=source_image,json=sourceImage" json:"source_image,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetMem() uint64 {
	if m != nil {
		return m.Mem
	}
	return 0
}

func (m *CreateRequest) GetCores() uint32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *CreateRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateRequest) GetSourceImage() string {
	if m != nil {
		return m.SourceImage
	}
	return ""
}

type DestroyRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DestroyRequest) Reset()                    { *m = DestroyRequest{} }
func (m *DestroyRequest) String() string            { return proto.CompactTextString(m) }
func (*DestroyRequest) ProtoMessage()               {}
func (*DestroyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DestroyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DestroyReply struct {
}

func (m *DestroyReply) Reset()                    { *m = DestroyReply{} }
func (m *DestroyReply) String() string            { return proto.CompactTextString(m) }
func (*DestroyReply) ProtoMessage()               {}
func (*DestroyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*VM)(nil), "api.VM")
	proto.RegisterType((*ListVMRequest)(nil), "api.ListVMRequest")
	proto.RegisterType((*ListVMReply)(nil), "api.ListVMReply")
	proto.RegisterType((*FindRequest)(nil), "api.FindRequest")
	proto.RegisterType((*CreateRequest)(nil), "api.CreateRequest")
	proto.RegisterType((*DestroyRequest)(nil), "api.DestroyRequest")
	proto.RegisterType((*DestroyReply)(nil), "api.DestroyReply")
	proto.RegisterEnum("api.FindRequest_FindBy", FindRequest_FindBy_name, FindRequest_FindBy_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VMRegistry service

type VMRegistryClient interface {
	List(ctx context.Context, in *ListVMRequest, opts ...grpc.CallOption) (*ListVMReply, error)
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*VM, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*VM, error)
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyReply, error)
}

type vMRegistryClient struct {
	cc *grpc.ClientConn
}

func NewVMRegistryClient(cc *grpc.ClientConn) VMRegistryClient {
	return &vMRegistryClient{cc}
}

func (c *vMRegistryClient) List(ctx context.Context, in *ListVMRequest, opts ...grpc.CallOption) (*ListVMReply, error) {
	out := new(ListVMReply)
	err := grpc.Invoke(ctx, "/api.VMRegistry/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMRegistryClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*VM, error) {
	out := new(VM)
	err := grpc.Invoke(ctx, "/api.VMRegistry/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMRegistryClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*VM, error) {
	out := new(VM)
	err := grpc.Invoke(ctx, "/api.VMRegistry/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMRegistryClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyReply, error) {
	out := new(DestroyReply)
	err := grpc.Invoke(ctx, "/api.VMRegistry/Destroy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VMRegistry service

type VMRegistryServer interface {
	List(context.Context, *ListVMRequest) (*ListVMReply, error)
	Find(context.Context, *FindRequest) (*VM, error)
	Create(context.Context, *CreateRequest) (*VM, error)
	Destroy(context.Context, *DestroyRequest) (*DestroyReply, error)
}

func RegisterVMRegistryServer(s *grpc.Server, srv VMRegistryServer) {
	s.RegisterService(&_VMRegistry_serviceDesc, srv)
}

func _VMRegistry_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMRegistryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VMRegistry/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMRegistryServer).List(ctx, req.(*ListVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMRegistry_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMRegistryServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VMRegistry/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMRegistryServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMRegistry_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMRegistryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VMRegistry/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMRegistryServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMRegistry_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMRegistryServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VMRegistry/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMRegistryServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.VMRegistry",
	HandlerType: (*VMRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _VMRegistry_List_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _VMRegistry_Find_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VMRegistry_Create_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _VMRegistry_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmregistry.proto",
}

func init() { proto.RegisterFile("vmregistry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0xab, 0xd3, 0x40,
	0x14, 0xc5, 0x9b, 0x3f, 0x2f, 0xc1, 0x9b, 0xd7, 0xbc, 0x78, 0x15, 0x8c, 0x5d, 0x3d, 0x47, 0xc1,
	0xe2, 0x22, 0x48, 0xdf, 0xce, 0x9d, 0xf6, 0x0f, 0x04, 0x8c, 0x94, 0x88, 0xdd, 0x96, 0xb4, 0x9d,
	0x96, 0x81, 0xa4, 0x19, 0x33, 0x69, 0x21, 0xee, 0xf4, 0x8b, 0xf9, 0xd5, 0x64, 0x6e, 0x52, 0x69,
	0x04, 0xdf, 0x2a, 0x67, 0x0e, 0x67, 0x66, 0x4e, 0x7e, 0x77, 0x20, 0x38, 0x17, 0x15, 0x3f, 0x08,
	0x55, 0x57, 0x4d, 0x24, 0xab, 0xb2, 0x2e, 0xd1, 0xca, 0xa4, 0x60, 0x1f, 0xc0, 0x5c, 0x25, 0x88,
	0x60, 0x1f, 0xb3, 0x82, 0x87, 0xc6, 0xbd, 0x31, 0x7e, 0x92, 0x92, 0xc6, 0x00, 0xac, 0x22, 0xdb,
	0x86, 0x26, 0x59, 0x5a, 0xa2, 0x0f, 0xa6, 0x90, 0xa1, 0x45, 0x86, 0x29, 0x24, 0xbb, 0x83, 0xe1,
	0x67, 0xa1, 0xea, 0x55, 0x92, 0xf2, 0xef, 0x27, 0xae, 0x6a, 0x36, 0x06, 0xef, 0x62, 0xc8, 0xbc,
	0xc1, 0x97, 0x60, 0x9d, 0x0b, 0x15, 0x1a, 0xf7, 0xd6, 0xd8, 0x9b, 0xb8, 0x51, 0x26, 0x45, 0xb4,
	0x4a, 0x52, 0xed, 0xb1, 0x9f, 0x06, 0x78, 0x0b, 0x71, 0xdc, 0x75, 0x3b, 0xf1, 0x3d, 0xb8, 0x7b,
	0x71, 0xdc, 0xad, 0x37, 0x0d, 0x75, 0xf0, 0x27, 0x2f, 0x28, 0x7e, 0x15, 0x21, 0xfd, 0xa9, 0x49,
	0x9d, 0x3d, 0x7d, 0xf1, 0x39, 0xdc, 0x9c, 0xb3, 0xfc, 0xc4, 0xbb, 0x82, 0xed, 0x82, 0xbd, 0x03,
	0xa7, 0xcd, 0xe1, 0x1d, 0x78, 0xdf, 0xbe, 0x7c, 0x5d, 0xce, 0xa7, 0xf1, 0x22, 0x9e, 0xcf, 0x82,
	0x01, 0x3a, 0x60, 0xc6, 0xcb, 0xc0, 0x40, 0x17, 0xac, 0xe4, 0xe3, 0x34, 0x30, 0xd9, 0x2f, 0x03,
	0x86, 0xd3, 0x8a, 0x67, 0x35, 0xbf, 0xb4, 0xf8, 0x1f, 0x06, 0x5e, 0xd0, 0x2d, 0x76, 0xaa, 0xa5,
	0xbe, 0x79, 0x5b, 0x56, 0x5c, 0x11, 0x89, 0x61, 0xda, 0x2e, 0xf4, 0x5e, 0x25, 0x7e, 0xf0, 0xd0,
	0xa6, 0x20, 0x69, 0x7c, 0x05, 0xb7, 0xaa, 0x3c, 0x55, 0x5b, 0xbe, 0x16, 0x45, 0x76, 0xe0, 0xe1,
	0x0d, 0x9d, 0xeb, 0xb5, 0x5e, 0xac, 0x2d, 0xf6, 0x06, 0xfc, 0x19, 0x57, 0x75, 0x55, 0x36, 0x8f,
	0x94, 0x60, 0x3e, 0xdc, 0xfe, 0x4d, 0xc9, 0xbc, 0x99, 0xfc, 0x36, 0x00, 0x34, 0xe5, 0x76, 0x9e,
	0x18, 0x81, 0xad, 0xb9, 0x23, 0x12, 0xb4, 0xde, 0x4c, 0x46, 0x41, 0xcf, 0x93, 0x79, 0xc3, 0x06,
	0xf8, 0x1a, 0x6c, 0x4d, 0x09, 0x83, 0x7f, 0x21, 0x8f, 0x2e, 0x53, 0x62, 0x03, 0x7c, 0x0b, 0x4e,
	0x4b, 0xa7, 0x3b, 0xb6, 0x87, 0xea, 0x3a, 0xf8, 0x00, 0x6e, 0x57, 0x0e, 0x9f, 0x91, 0xdb, 0xff,
	0xa1, 0xd1, 0xd3, 0xbe, 0x49, 0x15, 0x36, 0x0e, 0xbd, 0xc1, 0x87, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0x21, 0x49, 0x05, 0x97, 0x02, 0x00, 0x00,
}
